// import pizza1 from '../images/food-item/pizza/pizza1.jpg';

const fooditems =[
    {
        id:1,
        hotel_id:1,
        food_category:[
            {
            id:1,
            name:'Burger'
            },
            {
            id:2,
            name:'Pizza'
            },
            {
            id:3,
            name:'Sandwhich'
            },
            {
            id:4,
            name:'Ice-Cream'
            },
            {
            id:5,
            name:'Biryani'
            },
            {
            id:6,
            name:'Cake'
            }             
        ]
    },
    {
        id:2,
        hotel_id:2,
        food_category:[
            {
                id:1,
                name:'Cone'
                },
                {
                id:2,
                name:'Family Pack'
                },
                {
                id:3,
                name:'Cup'
                } 
        ]
    }, 
    {
        id:3,
        hotel_id:3,
        food_category:[
            {
                id:1,
                name:'Pizza'
                },
                {
                id:2,
                name:'Biryani'
                },
                {
                id:3,
                name:'Sandwhich'
                } 
        ]
    },
    {
        id:4,
        hotel_id:4,
        food_category:[
            {
                id:1,
                name:'Family Pack'
                },
                {
                id:2,
                name:'Delights In A CUP'
                },
                {
                id:3,
                name:'Feast'
                }
        ]
    }   
]

export default fooditems;